services:
  - type: web
    name: tilahun-site-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: BOT_TOKEN
        value: 8891345663:AAGdwG2CDqOPwXBou-reFvDWf8ZBsrMmwWM
      - key: SUPERGROUP_CHAT_ID
        value: "-1004307508548"
      - key: ADMIN_IDS
        value: "1602040402"
      - key: REQUIRE_APPROVAL
        value: "True"
      - key: TIMEZONE
        value: "Africa/Addis_Ababa"
      - key: GOOGLE_SHEET_WEBHOOK_URL
        value: "https://script.google.com/macros/s/AKfycbzAsdxZXnjBbiuHdy_VO8ukSLaWKIxLLkuALy6fjZ5Yk0jRJ5g9FyIWQh19K_3qscYqBg/exec"
      - key: DATABASE_URL
        value: ""
